[package]
name = "rust_tests"
version = "0.1.0"
authors = ["Angelo <angelorodem@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
colored = "1.9"
flatbuffers = "0.6.1"
tokio = "0.2.21"