// automatically generated by the FlatBuffers compiler, do not modify



use crate::Player_generated::*;
use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(non_camel_case_types)]
#[repr(i8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum StatusAnswerPlayer {
  OkNew = 0,
  OkLogin = 1,
  Denied = 2,
  Failure = 3,

}

pub const ENUM_MIN_STATUS_ANSWER_PLAYER: i8 = 0;
pub const ENUM_MAX_STATUS_ANSWER_PLAYER: i8 = 3;

impl<'a> flatbuffers::Follow<'a> for StatusAnswerPlayer {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for StatusAnswerPlayer {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = i8::to_le(self as i8);
    let p = &n as *const i8 as *const StatusAnswerPlayer;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = i8::from_le(self as i8);
    let p = &n as *const i8 as *const StatusAnswerPlayer;
    unsafe { *p }
  }
}

impl flatbuffers::Push for StatusAnswerPlayer {
    type Output = StatusAnswerPlayer;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<StatusAnswerPlayer>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_STATUS_ANSWER_PLAYER:[StatusAnswerPlayer; 4] = [
  StatusAnswerPlayer::OkNew,
  StatusAnswerPlayer::OkLogin,
  StatusAnswerPlayer::Denied,
  StatusAnswerPlayer::Failure
];

#[allow(non_camel_case_types)]
pub const ENUM_NAMES_STATUS_ANSWER_PLAYER:[&'static str; 4] = [
    "OkNew",
    "OkLogin",
    "Denied",
    "Failure"
];

pub fn enum_name_status_answer_player(e: StatusAnswerPlayer) -> &'static str {
  let index = e as i8;
  ENUM_NAMES_STATUS_ANSWER_PLAYER[index as usize]
}

pub enum AnswerPlayerOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct AnswerPlayer<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for AnswerPlayer<'a> {
    type Inner = AnswerPlayer<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> AnswerPlayer<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        AnswerPlayer {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args AnswerPlayerArgs<'args>) -> flatbuffers::WIPOffset<AnswerPlayer<'bldr>> {
      let mut builder = AnswerPlayerBuilder::new(_fbb);
      if let Some(x) = args.player { builder.add_player(x); }
      builder.add_status(args.status);
      builder.finish()
    }

    pub const VT_STATUS: flatbuffers::VOffsetT = 4;
    pub const VT_PLAYER: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn status(&self) -> StatusAnswerPlayer {
    self._tab.get::<StatusAnswerPlayer>(AnswerPlayer::VT_STATUS, Some(StatusAnswerPlayer::OkNew)).unwrap()
  }
  #[inline]
  pub fn player(&self) -> Option<Player<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<Player<'a>>>(AnswerPlayer::VT_PLAYER, None)
  }
}

pub struct AnswerPlayerArgs<'a> {
    pub status: StatusAnswerPlayer,
    pub player: Option<flatbuffers::WIPOffset<Player<'a >>>,
}
impl<'a> Default for AnswerPlayerArgs<'a> {
    #[inline]
    fn default() -> Self {
        AnswerPlayerArgs {
            status: StatusAnswerPlayer::OkNew,
            player: None,
        }
    }
}
pub struct AnswerPlayerBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> AnswerPlayerBuilder<'a, 'b> {
  #[inline]
  pub fn add_status(&mut self, status: StatusAnswerPlayer) {
    self.fbb_.push_slot::<StatusAnswerPlayer>(AnswerPlayer::VT_STATUS, status, StatusAnswerPlayer::OkNew);
  }
  #[inline]
  pub fn add_player(&mut self, player: flatbuffers::WIPOffset<Player<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Player>>(AnswerPlayer::VT_PLAYER, player);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> AnswerPlayerBuilder<'a, 'b> {
    let start = _fbb.start_table();
    AnswerPlayerBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<AnswerPlayer<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_answer_player<'a>(buf: &'a [u8]) -> AnswerPlayer<'a> {
  flatbuffers::get_root::<AnswerPlayer<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_answer_player<'a>(buf: &'a [u8]) -> AnswerPlayer<'a> {
  flatbuffers::get_size_prefixed_root::<AnswerPlayer<'a>>(buf)
}

#[inline]
pub fn finish_answer_player_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<AnswerPlayer<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_answer_player_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<AnswerPlayer<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
