// automatically generated by the FlatBuffers compiler, do not modify



use crate::Player_generated::*;
use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

pub enum AnswerOnlinePlayersOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct AnswerOnlinePlayers<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for AnswerOnlinePlayers<'a> {
    type Inner = AnswerOnlinePlayers<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> AnswerOnlinePlayers<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        AnswerOnlinePlayers {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args AnswerOnlinePlayersArgs<'args>) -> flatbuffers::WIPOffset<AnswerOnlinePlayers<'bldr>> {
      let mut builder = AnswerOnlinePlayersBuilder::new(_fbb);
      if let Some(x) = args.players { builder.add_players(x); }
      builder.finish()
    }

    pub const VT_PLAYERS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn players(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Player<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<Player<'a>>>>>(AnswerOnlinePlayers::VT_PLAYERS, None)
  }
}

pub struct AnswerOnlinePlayersArgs<'a> {
    pub players: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a , flatbuffers::ForwardsUOffset<Player<'a >>>>>,
}
impl<'a> Default for AnswerOnlinePlayersArgs<'a> {
    #[inline]
    fn default() -> Self {
        AnswerOnlinePlayersArgs {
            players: None,
        }
    }
}
pub struct AnswerOnlinePlayersBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> AnswerOnlinePlayersBuilder<'a, 'b> {
  #[inline]
  pub fn add_players(&mut self, players: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Player<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AnswerOnlinePlayers::VT_PLAYERS, players);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> AnswerOnlinePlayersBuilder<'a, 'b> {
    let start = _fbb.start_table();
    AnswerOnlinePlayersBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<AnswerOnlinePlayers<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_answer_online_players<'a>(buf: &'a [u8]) -> AnswerOnlinePlayers<'a> {
  flatbuffers::get_root::<AnswerOnlinePlayers<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_answer_online_players<'a>(buf: &'a [u8]) -> AnswerOnlinePlayers<'a> {
  flatbuffers::get_size_prefixed_root::<AnswerOnlinePlayers<'a>>(buf)
}

#[inline]
pub fn finish_answer_online_players_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<AnswerOnlinePlayers<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_answer_online_players_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<AnswerOnlinePlayers<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
