// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

pub enum AskForOnlinePlayersOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct AskForOnlinePlayers<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for AskForOnlinePlayers<'a> {
    type Inner = AskForOnlinePlayers<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> AskForOnlinePlayers<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        AskForOnlinePlayers {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args AskForOnlinePlayersArgs) -> flatbuffers::WIPOffset<AskForOnlinePlayers<'bldr>> {
      let mut builder = AskForOnlinePlayersBuilder::new(_fbb);
      builder.add_sequence(args.sequence);
      builder.finish()
    }

    pub const VT_SEQUENCE: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn sequence(&self) -> i32 {
    self._tab.get::<i32>(AskForOnlinePlayers::VT_SEQUENCE, Some(0)).unwrap()
  }
}

pub struct AskForOnlinePlayersArgs {
    pub sequence: i32,
}
impl<'a> Default for AskForOnlinePlayersArgs {
    #[inline]
    fn default() -> Self {
        AskForOnlinePlayersArgs {
            sequence: 0,
        }
    }
}
pub struct AskForOnlinePlayersBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> AskForOnlinePlayersBuilder<'a, 'b> {
  #[inline]
  pub fn add_sequence(&mut self, sequence: i32) {
    self.fbb_.push_slot::<i32>(AskForOnlinePlayers::VT_SEQUENCE, sequence, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> AskForOnlinePlayersBuilder<'a, 'b> {
    let start = _fbb.start_table();
    AskForOnlinePlayersBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<AskForOnlinePlayers<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_ask_for_online_players<'a>(buf: &'a [u8]) -> AskForOnlinePlayers<'a> {
  flatbuffers::get_root::<AskForOnlinePlayers<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_ask_for_online_players<'a>(buf: &'a [u8]) -> AskForOnlinePlayers<'a> {
  flatbuffers::get_size_prefixed_root::<AskForOnlinePlayers<'a>>(buf)
}

#[inline]
pub fn finish_ask_for_online_players_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<AskForOnlinePlayers<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_ask_for_online_players_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<AskForOnlinePlayers<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
