// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

pub enum AskForPlayerOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct AskForPlayer<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for AskForPlayer<'a> {
    type Inner = AskForPlayer<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> AskForPlayer<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        AskForPlayer {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args AskForPlayerArgs<'args>) -> flatbuffers::WIPOffset<AskForPlayer<'bldr>> {
      let mut builder = AskForPlayerBuilder::new(_fbb);
      if let Some(x) = args.password { builder.add_password(x); }
      if let Some(x) = args.name { builder.add_name(x); }
      builder.finish()
    }

    pub const VT_NAME: flatbuffers::VOffsetT = 4;
    pub const VT_PASSWORD: flatbuffers::VOffsetT = 6;

  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(AskForPlayer::VT_NAME, None)
  }
  #[inline]
  pub fn password(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(AskForPlayer::VT_PASSWORD, None)
  }
}

pub struct AskForPlayerArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub password: Option<flatbuffers::WIPOffset<&'a  str>>,
}
impl<'a> Default for AskForPlayerArgs<'a> {
    #[inline]
    fn default() -> Self {
        AskForPlayerArgs {
            name: None,
            password: None,
        }
    }
}
pub struct AskForPlayerBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> AskForPlayerBuilder<'a, 'b> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AskForPlayer::VT_NAME, name);
  }
  #[inline]
  pub fn add_password(&mut self, password: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AskForPlayer::VT_PASSWORD, password);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> AskForPlayerBuilder<'a, 'b> {
    let start = _fbb.start_table();
    AskForPlayerBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<AskForPlayer<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_ask_for_player<'a>(buf: &'a [u8]) -> AskForPlayer<'a> {
  flatbuffers::get_root::<AskForPlayer<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_ask_for_player<'a>(buf: &'a [u8]) -> AskForPlayer<'a> {
  flatbuffers::get_size_prefixed_root::<AskForPlayer<'a>>(buf)
}

#[inline]
pub fn finish_ask_for_player_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<AskForPlayer<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_ask_for_player_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<AskForPlayer<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
