// automatically generated by the FlatBuffers compiler, do not modify



use crate::Player_generated::*;
use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

pub enum OnlinePlayersOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct OnlinePlayers<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for OnlinePlayers<'a> {
    type Inner = OnlinePlayers<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> OnlinePlayers<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        OnlinePlayers {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args OnlinePlayersArgs<'args>) -> flatbuffers::WIPOffset<OnlinePlayers<'bldr>> {
      let mut builder = OnlinePlayersBuilder::new(_fbb);
      if let Some(x) = args.player { builder.add_player(x); }
      builder.finish()
    }

    pub const VT_PLAYER: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn player(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Player<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<Player<'a>>>>>(OnlinePlayers::VT_PLAYER, None)
  }
}

pub struct OnlinePlayersArgs<'a> {
    pub player: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a , flatbuffers::ForwardsUOffset<Player<'a >>>>>,
}
impl<'a> Default for OnlinePlayersArgs<'a> {
    #[inline]
    fn default() -> Self {
        OnlinePlayersArgs {
            player: None,
        }
    }
}
pub struct OnlinePlayersBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> OnlinePlayersBuilder<'a, 'b> {
  #[inline]
  pub fn add_player(&mut self, player: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Player<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(OnlinePlayers::VT_PLAYER, player);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> OnlinePlayersBuilder<'a, 'b> {
    let start = _fbb.start_table();
    OnlinePlayersBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<OnlinePlayers<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_online_players<'a>(buf: &'a [u8]) -> OnlinePlayers<'a> {
  flatbuffers::get_root::<OnlinePlayers<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_online_players<'a>(buf: &'a [u8]) -> OnlinePlayers<'a> {
  flatbuffers::get_size_prefixed_root::<OnlinePlayers<'a>>(buf)
}

#[inline]
pub fn finish_online_players_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<OnlinePlayers<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_online_players_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<OnlinePlayers<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
