// automatically generated by the FlatBuffers compiler, do not modify



use crate::GameResult_generated::*;
use crate::Player_generated::*;
use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

#[allow(non_camel_case_types)]
#[repr(i8)]
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum Status {
  Ok = 0,
  Fail = 1,

}

pub const ENUM_MIN_STATUS: i8 = 0;
pub const ENUM_MAX_STATUS: i8 = 1;

impl<'a> flatbuffers::Follow<'a> for Status {
  type Inner = Self;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::read_scalar_at::<Self>(buf, loc)
  }
}

impl flatbuffers::EndianScalar for Status {
  #[inline]
  fn to_little_endian(self) -> Self {
    let n = i8::to_le(self as i8);
    let p = &n as *const i8 as *const Status;
    unsafe { *p }
  }
  #[inline]
  fn from_little_endian(self) -> Self {
    let n = i8::from_le(self as i8);
    let p = &n as *const i8 as *const Status;
    unsafe { *p }
  }
}

impl flatbuffers::Push for Status {
    type Output = Status;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        flatbuffers::emplace_scalar::<Status>(dst, *self);
    }
}

#[allow(non_camel_case_types)]
pub const ENUM_VALUES_STATUS:[Status; 2] = [
  Status::Ok,
  Status::Fail
];

#[allow(non_camel_case_types)]
pub const ENUM_NAMES_STATUS:[&'static str; 2] = [
    "Ok",
    "Fail"
];

pub fn enum_name_status(e: Status) -> &'static str {
  let index = e as i8;
  ENUM_NAMES_STATUS[index as usize]
}

pub enum SendGameScoreOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct SendGameScore<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SendGameScore<'a> {
    type Inner = SendGameScore<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> SendGameScore<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        SendGameScore {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args SendGameScoreArgs<'args>) -> flatbuffers::WIPOffset<SendGameScore<'bldr>> {
      let mut builder = SendGameScoreBuilder::new(_fbb);
      if let Some(x) = args.score_message { builder.add_score_message(x); }
      if let Some(x) = args.game_result { builder.add_game_result(x); }
      if let Some(x) = args.player { builder.add_player(x); }
      builder.add_status(args.status);
      builder.finish()
    }

    pub const VT_PLAYER: flatbuffers::VOffsetT = 4;
    pub const VT_GAME_RESULT: flatbuffers::VOffsetT = 6;
    pub const VT_SCORE_MESSAGE: flatbuffers::VOffsetT = 8;
    pub const VT_STATUS: flatbuffers::VOffsetT = 10;

  #[inline]
  pub fn player(&self) -> Option<Player<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<Player<'a>>>(SendGameScore::VT_PLAYER, None)
  }
  #[inline]
  pub fn game_result(&self) -> Option<GameResult<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<GameResult<'a>>>(SendGameScore::VT_GAME_RESULT, None)
  }
  #[inline]
  pub fn score_message(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SendGameScore::VT_SCORE_MESSAGE, None)
  }
  #[inline]
  pub fn status(&self) -> Status {
    self._tab.get::<Status>(SendGameScore::VT_STATUS, Some(Status::Ok)).unwrap()
  }
}

pub struct SendGameScoreArgs<'a> {
    pub player: Option<flatbuffers::WIPOffset<Player<'a >>>,
    pub game_result: Option<flatbuffers::WIPOffset<GameResult<'a >>>,
    pub score_message: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub status: Status,
}
impl<'a> Default for SendGameScoreArgs<'a> {
    #[inline]
    fn default() -> Self {
        SendGameScoreArgs {
            player: None,
            game_result: None,
            score_message: None,
            status: Status::Ok,
        }
    }
}
pub struct SendGameScoreBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> SendGameScoreBuilder<'a, 'b> {
  #[inline]
  pub fn add_player(&mut self, player: flatbuffers::WIPOffset<Player<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Player>>(SendGameScore::VT_PLAYER, player);
  }
  #[inline]
  pub fn add_game_result(&mut self, game_result: flatbuffers::WIPOffset<GameResult<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<GameResult>>(SendGameScore::VT_GAME_RESULT, game_result);
  }
  #[inline]
  pub fn add_score_message(&mut self, score_message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SendGameScore::VT_SCORE_MESSAGE, score_message);
  }
  #[inline]
  pub fn add_status(&mut self, status: Status) {
    self.fbb_.push_slot::<Status>(SendGameScore::VT_STATUS, status, Status::Ok);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> SendGameScoreBuilder<'a, 'b> {
    let start = _fbb.start_table();
    SendGameScoreBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SendGameScore<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_send_game_score<'a>(buf: &'a [u8]) -> SendGameScore<'a> {
  flatbuffers::get_root::<SendGameScore<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_send_game_score<'a>(buf: &'a [u8]) -> SendGameScore<'a> {
  flatbuffers::get_size_prefixed_root::<SendGameScore<'a>>(buf)
}

#[inline]
pub fn finish_send_game_score_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<SendGameScore<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_send_game_score_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<SendGameScore<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
