// automatically generated by the FlatBuffers compiler, do not modify



use crate::Player_generated::*;
use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

// struct GameResult, aligned to 8
#[repr(C, align(8))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct GameResult {
  hits_: u32,
  specials_: u32,
  misses_: u32,
  padding0__: u32,
  score_: i64,
} // pub struct GameResult
impl flatbuffers::SafeSliceAccess for GameResult {}
impl<'a> flatbuffers::Follow<'a> for GameResult {
  type Inner = &'a GameResult;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a GameResult>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a GameResult {
  type Inner = &'a GameResult;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<GameResult>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for GameResult {
    type Output = GameResult;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(self as *const GameResult as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b GameResult {
    type Output = GameResult;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::std::slice::from_raw_parts(*self as *const GameResult as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}


impl GameResult {
  pub fn new<'a>(_hits: u32, _specials: u32, _misses: u32, _score: i64) -> Self {
    GameResult {
      hits_: _hits.to_little_endian(),
      specials_: _specials.to_little_endian(),
      misses_: _misses.to_little_endian(),
      score_: _score.to_little_endian(),

      padding0__: 0,
    }
  }
  pub fn hits<'a>(&'a self) -> u32 {
    self.hits_.from_little_endian()
  }
  pub fn specials<'a>(&'a self) -> u32 {
    self.specials_.from_little_endian()
  }
  pub fn misses<'a>(&'a self) -> u32 {
    self.misses_.from_little_endian()
  }
  pub fn score<'a>(&'a self) -> i64 {
    self.score_.from_little_endian()
  }
}

pub enum SendGameScoreOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct SendGameScore<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SendGameScore<'a> {
    type Inner = SendGameScore<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> SendGameScore<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        SendGameScore {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args SendGameScoreArgs<'args>) -> flatbuffers::WIPOffset<SendGameScore<'bldr>> {
      let mut builder = SendGameScoreBuilder::new(_fbb);
      if let Some(x) = args.score_message { builder.add_score_message(x); }
      if let Some(x) = args.game_result { builder.add_game_result(x); }
      if let Some(x) = args.player { builder.add_player(x); }
      builder.finish()
    }

    pub const VT_PLAYER: flatbuffers::VOffsetT = 4;
    pub const VT_GAME_RESULT: flatbuffers::VOffsetT = 6;
    pub const VT_SCORE_MESSAGE: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn player(&self) -> Option<Player<'a>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<Player<'a>>>(SendGameScore::VT_PLAYER, None)
  }
  #[inline]
  pub fn game_result(&self) -> Option<&'a GameResult> {
    self._tab.get::<GameResult>(SendGameScore::VT_GAME_RESULT, None)
  }
  #[inline]
  pub fn score_message(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SendGameScore::VT_SCORE_MESSAGE, None)
  }
}

pub struct SendGameScoreArgs<'a> {
    pub player: Option<flatbuffers::WIPOffset<Player<'a >>>,
    pub game_result: Option<&'a  GameResult>,
    pub score_message: Option<flatbuffers::WIPOffset<&'a  str>>,
}
impl<'a> Default for SendGameScoreArgs<'a> {
    #[inline]
    fn default() -> Self {
        SendGameScoreArgs {
            player: None,
            game_result: None,
            score_message: None,
        }
    }
}
pub struct SendGameScoreBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> SendGameScoreBuilder<'a, 'b> {
  #[inline]
  pub fn add_player(&mut self, player: flatbuffers::WIPOffset<Player<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Player>>(SendGameScore::VT_PLAYER, player);
  }
  #[inline]
  pub fn add_game_result(&mut self, game_result: &'b  GameResult) {
    self.fbb_.push_slot_always::<&GameResult>(SendGameScore::VT_GAME_RESULT, game_result);
  }
  #[inline]
  pub fn add_score_message(&mut self, score_message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SendGameScore::VT_SCORE_MESSAGE, score_message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> SendGameScoreBuilder<'a, 'b> {
    let start = _fbb.start_table();
    SendGameScoreBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SendGameScore<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

#[inline]
pub fn get_root_as_send_game_score<'a>(buf: &'a [u8]) -> SendGameScore<'a> {
  flatbuffers::get_root::<SendGameScore<'a>>(buf)
}

#[inline]
pub fn get_size_prefixed_root_as_send_game_score<'a>(buf: &'a [u8]) -> SendGameScore<'a> {
  flatbuffers::get_size_prefixed_root::<SendGameScore<'a>>(buf)
}

#[inline]
pub fn finish_send_game_score_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<SendGameScore<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_send_game_score_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<SendGameScore<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
