[package]
name = "Server"
version = "0.1.0"
authors = ["Angelo <angelorodem@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "0.6.1"
tokio = { version = "0.2.21", features = ["full"] }